name: Build

on:
  # Currently runs on dispatch to allow for easier development of CI
  workflow_dispatch:
  push:
    branches: [ci-setup]

jobs:
  build: # Can be named anything.
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Change this later (or not?). Allows to check both OSes during testing easily.
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout (with submodules)
        # Can either be "uses" (prebuilt actions) or "run" (execute shell command).
        uses: actions/checkout@v4 # Unsure if i need to pin verison here?
        with:
          submodules: recursive

      - name: Environment setup (Linux)
        # Windows latest should already have all these installed so only install for Linux.
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang libc++-dev libc++abi-dev

      - name: Show environment 
        shell: bash # Allows for usage of similar commands between Win and Linux.
        run: |
          echo --- Versions ---
          echo "Clang version: $(clang --version | head -n 1)"
          echo "Ninja version: $(ninja --version)"
          echo "CMake version: $(cmake --version | head -n 1)"

